# Generated by Django 5.0.6 on 2024-07-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stb_loader', '0005_alter_loaderstatus_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='distance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('blok_loading', models.FloatField()),
                ('elevasi_loading', models.IntegerField()),
                ('lokasi_dumping', models.CharField(max_length=20)),
                ('elevasi_dumping', models.IntegerField()),
                ('horizontal_distance', models.FloatField()),
                ('lokasi', models.CharField(max_length=10)),
                ('vertical_distance', models.FloatField()),
                ('loader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stb_loader.loaderid')),
            ],
        ),
    ]
