# Generated by Django 5.0.6 on 2024-07-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distance", "0004_alter_distance_elevasi_dumping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distance",
            name="elevasi_loading",
            field=models.FloatField(),
        ),
    ]
