# Generated by Django 5.0.6 on 2024-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hmOperator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('equipment', models.CharField(max_length=10)),
                ('operator', models.CharField(max_length=40)),
                ('NRP', models.IntegerField(max_length=10)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
                ('hm_start', models.FloatField(null=True)),
                ('hm_end', models.FloatField(null=True)),
            ],
        ),
    ]
