# Generated by Django 5.0.6 on 2024-07-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmoperator',
            name='NRP',
            field=models.IntegerField(),
        ),
    ]
