# Generated by Django 5.0.6 on 2024-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0002_alter_hmoperator_nrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmoperator',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
