# Generated by Django 5.0.6 on 2024-07-12 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hm", "0003_alter_hmoperator_logout_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("NRP", models.IntegerField(primary_key=True, serialize=False)),
                ("operator", models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name="hmoperator",
            name="operator",
        ),
        migrations.AlterField(
            model_name="hmoperator",
            name="NRP",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hm.operator"
            ),
        ),
    ]
