# Generated by Django 5.0.6 on 2024-06-19 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stb_loader', '0003_rename_unitid_loaderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='truckID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jigsaw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ritase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField()),
                ('shift', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('time_full', models.DateTimeField(null=True)),
                ('truck_id', models.CharField(max_length=20)),
                ('material_id', models.CharField(max_length=20)),
                ('loader_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stb_loader.loaderid')),
            ],
        ),
    ]
