# Generated by Django 5.0.6 on 2024-06-19 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritase',
            name='truck_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ritase.truckid'),
        ),
    ]
