# Generated by Django 5.0.6 on 2024-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0002_alter_ritase_truck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritase',
            name='blast_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ritase',
            name='dump_location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ritase',
            name='grade_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ritase',
            name='time_empty',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ritase',
            name='time_full',
            field=models.DateTimeField(),
        ),
    ]
