# Generated by Django 5.0.6 on 2024-06-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0003_ritase_blast_id_ritase_dump_location_ritase_grade_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ritase',
            old_name='blast_id',
            new_name='blast',
        ),
        migrations.RenameField(
            model_name='ritase',
            old_name='grade_id',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='ritase',
            old_name='material_id',
            new_name='material',
        ),
        migrations.AddField(
            model_name='ritase',
            name='load_id',
            field=models.IntegerField(null=True),
        ),
    ]
