# Generated by Django 5.0.6 on 2024-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0004_rename_blast_id_ritase_blast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritase',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
