# Generated by Django 5.0.6 on 2024-06-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0006_truckid_ob_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritase',
            name='report_date',
            field=models.DateField(null=True),
        ),
    ]
