# Generated by Django 5.0.6 on 2024-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0007_ritase_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='cek_ritase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField()),
                ('shift', models.IntegerField()),
                ('hauler', models.CharField(max_length=10)),
                ('NRP', models.IntegerField(null=True)),
                ('hm_start', models.FloatField(null=True)),
                ('hm_end', models.FloatField(null=True)),
                ('loader', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=10, null=True)),
                ('a', models.SmallIntegerField()),
                ('b', models.SmallIntegerField()),
                ('c', models.SmallIntegerField()),
                ('d', models.SmallIntegerField()),
                ('f', models.SmallIntegerField()),
                ('g', models.SmallIntegerField()),
                ('h', models.SmallIntegerField()),
                ('i', models.SmallIntegerField()),
                ('j', models.SmallIntegerField()),
                ('k', models.SmallIntegerField()),
                ('l', models.SmallIntegerField()),
                ('m', models.SmallIntegerField()),
                ('n', models.SmallIntegerField()),
            ],
        ),
    ]
