# Generated by Django 5.0.6 on 2024-07-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0008_cek_ritase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cek_ritase',
            old_name='n',
            new_name='e',
        ),
    ]
