# Generated by Django 5.0.6 on 2024-07-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritase', '0009_rename_n_cek_ritase_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cek_ritase',
            name='NRP',
        ),
        migrations.RemoveField(
            model_name='cek_ritase',
            name='hm_end',
        ),
        migrations.RemoveField(
            model_name='cek_ritase',
            name='hm_start',
        ),
        migrations.AddField(
            model_name='cek_ritase',
            name='operator_hauler_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cek_ritase',
            name='operator_loader_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
