# Generated by Django 5.0.6 on 2024-07-20 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ritase", "0011_truckid_code_truckid_ellipse"),
    ]

    operations = [
        migrations.CreateModel(
            name="material",
            fields=[
                (
                    "code",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("material", models.CharField(max_length=10)),
                ("remark", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="cek_ritase",
            name="material",
        ),
        migrations.RemoveField(
            model_name="cek_ritase",
            name="remark",
        ),
        migrations.AddField(
            model_name="cek_ritase",
            name="code_material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ritase.material",
            ),
        ),
    ]
