# Generated by Django 5.0.6 on 2024-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ritase", "0012_material_remove_cek_ritase_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ritase",
            name="load_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
