# Generated by Django 5.0.6 on 2024-06-13 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('standby_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UnitID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoaderStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date', models.DateField()),
                ('hour', models.SmallIntegerField()),
                ('shift', models.SmallIntegerField()),
                ('timeStart', models.DateTimeField()),
                ('timeEnd', models.DateTimeField()),
                ('standby_code', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stb_loader.unitid')),
            ],
        ),
    ]
