# Generated by Django 5.0.6 on 2024-06-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stb_loader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaderstatus',
            name='timeEnd',
        ),
    ]
