# Generated by Django 5.0.6 on 2024-06-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb_loader', '0004_loaderstatus_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaderstatus',
            name='report_date',
            field=models.DateField(),
        ),
    ]
