# Generated by Django 5.0.6 on 2024-07-14 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0005_alter_loaderstatus_report_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterLoader",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("date", models.DateField()),
                ("cluster", models.CharField(max_length=20)),
                ("pit", models.CharField(max_length=10)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stb_loader.loaderid",
                    ),
                ),
            ],
        ),
    ]
