# Generated by Django 5.0.6 on 2024-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0007_clusterloader_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterloader",
            name="hour",
            field=models.IntegerField(),
        ),
    ]
