# Generated by Django 5.0.6 on 2024-07-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0008_alter_clusterloader_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterloader",
            name="cluster",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="clusterloader",
            name="pit",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
