# Generated by Django 5.0.6 on 2024-07-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0009_alter_clusterloader_cluster_alter_clusterloader_pit"),
    ]

    operations = [
        migrations.AddField(
            model_name="loaderid",
            name="ellipse",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
