# Generated by Django 5.0.6 on 2024-08-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0011_loaderstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="loaderstatushistory",
            name="token",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
