# Generated by Django 5.0.6 on 2024-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0012_loaderstatushistory_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaderstatushistory",
            name="token",
            field=models.CharField(max_length=20),
        ),
    ]
