# Generated by Django 5.0.6 on 2024-08-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0013_alter_loaderstatushistory_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaderstatushistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("addBatch", "AddBatch"),
                ],
                max_length=10,
            ),
        ),
    ]
