# Generated by Django 5.0.6 on 2024-08-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0014_alter_loaderstatushistory_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="loaderstatus",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stb_loader.clusterloader",
            ),
        ),
    ]
