# Generated by Django 5.0.6 on 2024-08-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0016_standby_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standby",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="standby",
            name="color",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="standby",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
