# Generated by Django 5.0.6 on 2024-08-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0017_alter_standby_code_alter_standby_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reason",
            name="reason",
            field=models.CharField(max_length=60),
        ),
    ]
