# Generated by Django 5.0.6 on 2024-09-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0018_alter_reason_reason"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="loaderstatus",
            constraint=models.UniqueConstraint(
                fields=("date", "shift", "hour", "timeStart", "unit", "report_date"),
                name="unique_loader_status",
            ),
        ),
    ]
