# Generated by Django 5.0.6 on 2024-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stb_loader", "0019_loaderstatus_unique_loader_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaderstatushistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("addBatch", "AddBatch"),
                    ("updateBtch", "UpdateBtch"),
                ],
                max_length=10,
            ),
        ),
    ]
